version: '3.8'

services:
  # Commented out - using local PostgreSQL instance instead
  # postgres:
  #   image: postgres:15
  #   container_name: manna-postgres
  #   environment:
  #     POSTGRES_DB: manna_dev
  #     POSTGRES_USER: manna
  #     POSTGRES_PASSWORD: manna
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U manna -d manna_dev']
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  redis:
    image: redis:7-alpine
    container_name: manna-redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    container_name: manna-backend
    environment:
      - ENVIRONMENT=development
      # Using local PostgreSQL: database=manna, user=postgres, no password
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres@host.docker.internal:5432/manna}
      - REDIS_URL=redis://redis:6379/0
      - PLAID_CLIENT_ID=${PLAID_CLIENT_ID}
      - PLAID_SECRET=${PLAID_SECRET}
      - PLAID_ENVIRONMENT=${PLAID_ENVIRONMENT}
    ports:
      - '8001:8000'
    volumes:
      - ./packages/backend:/app
      - ./data:/app/data
      - ./reports:/app/reports
      - ./tools:/app/tools
    depends_on:
      # postgres dependency removed - using local instance
      redis:
        condition: service_healthy
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    container_name: manna-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    ports:
      - '3000:3000'
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - /app/packages/frontend/node_modules
      - /app/packages/frontend/.next
    depends_on:
      - backend
    command: pnpm dev

volumes:
  postgres_data:
  redis_data:
