[global]
dataFrameSerialization = "legacy"

[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
runOnSave = true
allowRunOnSave = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"