-- Fix for Plaid sync schema issues
-- Generated by fix_sync_schema.py
-- This SQL adds the missing columns required for Plaid transaction sync

-- Add critical missing columns
ALTER TABLE plaid_items ADD COLUMN last_sync_attempt TIMESTAMP WITH TIME ZONE;
ALTER TABLE plaid_items ADD COLUMN status VARCHAR(20) DEFAULT 'active' NOT NULL;
ALTER TABLE plaid_items ADD COLUMN error_code VARCHAR(50);
ALTER TABLE plaid_items ADD COLUMN error_message TEXT;
ALTER TABLE plaid_items ADD COLUMN requires_reauth BOOLEAN DEFAULT false;

-- Migrate existing error data if any
UPDATE plaid_items SET error_message = error WHERE error IS NOT NULL AND error != '';

-- Drop old error column
ALTER TABLE plaid_items DROP COLUMN IF EXISTS error;

-- Rename last_failed_sync to match model expectations
ALTER TABLE plaid_items RENAME COLUMN last_failed_sync TO last_sync_attempt_old;
UPDATE plaid_items SET last_sync_attempt = last_sync_attempt_old WHERE last_sync_attempt_old IS NOT NULL;
ALTER TABLE plaid_items DROP COLUMN last_sync_attempt_old;

-- Add performance indexes
CREATE INDEX IF NOT EXISTS idx_plaid_items_sync_status ON plaid_items(status, last_sync_attempt);
CREATE INDEX IF NOT EXISTS idx_plaid_items_cursor ON plaid_items(cursor) WHERE cursor IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_plaid_items_reauth ON plaid_items(requires_reauth, is_active);

-- Add data integrity constraints
ALTER TABLE plaid_items ADD CONSTRAINT ck_plaid_item_status CHECK (status IN ('active', 'error', 'expired', 'revoked', 'pending'));

-- Set existing items to active status if they don't have errors
UPDATE plaid_items SET status = 'active' WHERE status IS NULL AND error_message IS NULL;
UPDATE plaid_items SET status = 'error' WHERE status IS NULL AND error_message IS NOT NULL;

-- Add any missing columns that might be expected by the model
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS max_days_back INTEGER DEFAULT 730;
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS sync_frequency_hours INTEGER DEFAULT 6;
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS has_mfa BOOLEAN DEFAULT false;
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS update_type VARCHAR(20);
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS extra_data JSONB;
ALTER TABLE plaid_items ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1 NOT NULL;

-- Ensure proper column types for JSON fields
-- Note: This might need adjustment based on your PostgreSQL version
ALTER TABLE plaid_items ALTER COLUMN available_products TYPE JSONB USING available_products::jsonb;
ALTER TABLE plaid_items ALTER COLUMN billed_products TYPE JSONB USING billed_products::jsonb;

-- Final verification query
-- You can run this to check the schema after applying the fixes
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'plaid_items'
-- ORDER BY ordinal_position;